export const settings:Object = {
  actions: {
    custom: [
      {
        name: 'ver',
        title: '<i class="nb-list" data-toggle="tooltip" data-placement="top" title="Ejemplos"></i>',
      },
      {
        name: 'editar',
        title: '<i class="nb-edit" data-toggle="tooltip" data-placement="top" data-bs-html="true" title="Editar"></i>',
      },
      {
        name: 'eliminar',
        title: '<i data-toggle="tooltip" data-placement="top" title="Eliminar" class="nb-trash"></i>',
      }
    ],
  },
  columns: {
    id: {
      title: 'ID',
      type: 'number',
      filter: false
    },
    nombre: {
      title: 'Nombre',
      type: 'string',
      filter: false
    },
    descripcion: {
      title: 'Descripción',
      type: 'string',
      filter: false
    },
    identificador: {
      title: 'Identificador',
      type: 'string',
      filter: false
    },
    modulo: {
      title: 'Módulo',
      type: 'string',
      filter: false
    },
  },
};

export const data:Array<Object> = [
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 4,
    nombre: 'Patricia Lebsack',
    descripcion: 'Julianne.OConner@kory.org',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 5,
    nombre: 'Chelsey Dietrich',
    descripcion: 'Lucio_Hettinger@annie.ca',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 6,
    nombre: 'Mrs. Dennis Schulist',
    descripcion: 'Karley_Dach@jasper.info',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 7,
    nombre: 'Kurtis Weissnat',
    descripcion: 'Telly.Hoeger@billy.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 8,
    nombre: 'Nicholas Runolfsdottir V',
    descripcion: 'Sherwood@rosamond.me',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },
  {
    id: 9,
    nombre: 'Glenna Reichert',
    descripcion: 'Chaim_McDermott@dana.io',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 10,
    nombre: 'Clementina DuBuque',
    descripcion: 'Rey.Padberg@karina.biz',
    identificador: 'No',
    modulo: 'Modulo 1',
  },
  {
    id: 11,
    nombre: 'Nicholas DuBuque',
    descripcion: 'Rey.Padberg@rosamond.biz',
    identificador: 'Yes',
    modulo: 'Modulo 1',
  },

];

export const optionsAlgoritmos = [{value:"1", name:"Algoritmo de Regresión"}, {value:"2", name:"Algoritmo de Árbol de Desición",}];
export const optionsModulo = [{value:"1", name:"Aálisis de imágenes"}, {value:"2", name:"Análisis de Trayectorias"}, {value:"2", name:"Parametrización"}];
export const optionsServicios = [{value:"1", name:"Máquina EC2"}];
export const optionsAnalisis = [{value:"1", name:"Offline"}, {value:"2", name:"Online"}]
